<?php

namespace EventBundle\Repository;

/**
 * eventcoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventcoursRepository extends \Doctrine\ORM\EntityRepository
{
}
