<?php

namespace FournisseurBundle\Repository;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends \Doctrine\ORM\EntityRepository
{
}
