<?php

namespace FournisseurBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function affecter($id,$idd)
    {
        $Query = $this->getEntityManager()->createQuery(
            "update FournisseurBundle:fournisseur f set f.depot = :idd where f.id = :id " //update FournisseurBundle:Depot set capacite = capacite-1 where id = :idd
        )
        ->setParameter('id',$id)
        ->setParameter('idd',$idd);

        return $Query->getResult();
    }
}
