<?php

namespace test\Bundle\Repository;

/**
 * FournisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisRepository extends \Doctrine\ORM\EntityRepository
{
}
