<?php

namespace test\Bundle\Repository;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findbyMe($id)
    {
        $Query=$this->getEntityManager()
            ->createQuery("SELECT l FROM testBundle:Product l JOIN l.category lc
         WHERE lc.id=:id ")->setParameter('id',$id);

        return $Query->getResult();

    }
}
