fournisseur_homepage:
    path:     /back/fournisseurs
    defaults: { _controller: FournisseurBundle:Default:showFournisseur }

addF:
    path:     /back/add_F
    defaults: { _controller: FournisseurBundle:Default:addFournisseur }

editF:
    path:     /back/edit_F/{id}
    defaults: { _controller: FournisseurBundle:Default:editFournissuer}

deleteF:
    path:     /back/delete_F/{id}
    defaults: { _controller: FournisseurBundle:Default:deleteFournisseur}


depot_homepage:
    path:     /back/depots
    defaults: { _controller: FournisseurBundle:Default:showDepot }
addD:
    path:     /back/add_D
    defaults: { _controller: FournisseurBundle:Default:addDepot }

editD:
    path:     /back/edit_D/{id}
    defaults: { _controller: FournisseurBundle:Default:editDepot }

deleteD:
    path:     /back/delete_D/{id}
    defaults: { _controller: FournisseurBundle:Default:deleteDepot }
detailD:
    path:     /back/details/{id}
    defaults: { _controller: FournisseurBundle:Default:details }
affectD:
    path:     /back/affect_D/{id}
    defaults: { _controller: FournisseurBundle:Default:showDepotAffect }
affecterD:
    path:     /back/affect_D/{id}/{idd}
    defaults: { _controller: FournisseurBundle:Default:affecterDepot }
affiche_front:
    path:     /front/depots
    defaults: { _controller: FournisseurBundle:Default:afficher }
