lignecommande_index:
    path:     /
    defaults: { _controller: "VenteBundle:LigneCommande:index" }
    methods:  GET

lignecommande_show:
    path:     /{id}/show
    defaults: { _controller: "VenteBundle:LigneCommande:show" }
    methods:  GET



