<?php

namespace EventBundle\Repository;

/**
 * participantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class participantRepository extends \Doctrine\ORM\EntityRepository
{
}
