vente_livreur:
    resource: "@VenteBundle/Resources/config/routing/livreur.yml"
    prefix:   /livreur

Vente_Commande:
    resource: "@VenteBundle/Resources/config/routing/commande.yml"
    prefix:   /commande
Vente_LigneCommande:
    resource: "@VenteBundle/Resources/config/routing/lignecommande.yml"
    prefix:   /lignecommande

vente_homepage:
    path:     /a
    defaults: { _controller: VenteBundle:Default:index }
addProduit:
    path:     /addProduit/{idp}/{qte}
    defaults: { _controller: VenteBundle:Default:addProduit }
setProduit:
    path:     /setProduit/{idp}/{qte}
    defaults: { _controller: VenteBundle:Default:setProduit }

commande_index_front:
    path:     /commandefront
    defaults: { _controller: "VenteBundle:Commande:indexFront" }
    methods:  GET
card:
    path:     /card
    defaults: { _controller: VenteBundle:Default:Panier }

CheckOut:
    path:     /CheckOut
    defaults: { _controller: VenteBundle:Default:CheckOut }
